export const genreData = [
    "Action",
    "Adventure",
    "Role-Playing",
    "Shooter",
    "Platformer",
    "Puzzle",
    "Racing",
    "Sports",
    "Simulation",
    "Strategy",
    "Survival",
    "Horror",
    "Fighting",
    "Open World",
    "Stealth",
    "Rhythm",
    "MMORPG",
    "Metroidvania",
    "Sandbox",
    "Visual Novel",
    "Tactical",
    "Roguelike",
    "Battle Royale",
  ];

export const platformData = [
  "PC",
  "XBOX",
  "Playstation",
]